### ISSUE TITLE
Change Ports

### ISSUE THREAD

**Issue by bcook177** [andrewglass3/unmsCentos#1]
Would it be possible to change the ports on the services since on my CentOS server I already have apache running on 80 and 443 and Unifi running on 8443.

Getting the following errors when running the script.

![image](https://user-images.githubusercontent.com/38479667/38904448-a13fe136-4267-11e8-983d-4049a710f02f.png)

**Comment by andrewglass3** [comment]
Hi if you follow the official guide you can change the ports:

[https://help.ubnt.com/hc/en-us/articles/360000119728#5](url)

Id suggest editing https://github.com/andrewglass3/unmsCentos/blob/master/install.sh#L38 and appending --http-port 8080 --https-port 8843 or something similar (depending what ports you have free) then running the script and see what happens?

For me line 38 would look like this:
curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh --http-port 8080 --https-port 8843

Let me know how it goes?

Thanks 

Andrew

**Comment by bcook177** [comment]
Thanks Andrew that worked perfectly no issues to report other than changing the ports a little bit since 8080 and 8843 was already used by another application.

 

Thanks,

Brandon Cook

 <mailto:brandon.g.cook@comcast.net> brandon.g.cook@comcast.net

801-810-8004

**Comment by andrewglass3** [comment]
Thats great! Glad I could help :)
