### ISSUE TITLE
ERROR: Failed to Setup IP tables

### ISSUE THREAD

**Issue by jackouille-ch** [andrewglass3/unmsCentos#3]
Hi,

I am used CentOS 7 and tried to install CNMS with your script but I'm blocked with following error:
unms uses an image, skipping
rabbitmq uses an image, skipping
nginx uses an image, skipping
Stopping docker containers.
Removing network unms_internal
WARNING: Network unms_internal not found.
Removing network unms_public
WARNING: Network unms_public not found.
Checking available ports
Creating docker-compose.yml
Deploying templates
Writing config file
no crontab for unms
Deleting old firmwares from /home/unms/data/firmwares/unms/*
Starting docker containers.
Creating network "unms_internal" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable DROP INCOMING rule:  (iptables failed: iptables --wait -I DOCKER-ISOLATION-STAGE-1 -i br-76196d234c58 ! -d 172.19.0.0/16 -j DROP: iptables: No chain/target/match by that name.
 (exit status 1))
Failed to start docker containers
[root@unms tmp]#

I run the script as root and iptables is installed and in use, so iptable service is either installed. Any idea how to solve this issue?

**Comment by jackouille-ch** [comment]
Problem solved by adding manual entries in iptables.

**Comment by cedomichi** [comment]
Hello i have the same problem here. Can you show me what command did you enter?
